# @package _global_
data:
  dataset: ek12
  source_train_file: "txt/epic-kitchens/D1_train_source.txt"
  target_train_file: "txt/epic-kitchens/D2_train_target.txt"
  test_file: "txt/epic-kitchens/D2_test_target.txt"
  source_dataset: D1
  target_dataset: D2
  root: "dataset/epic-kitchens"