# @package _global_
data:
  dataset: hmdb_ucf
  source_train_file: "txt/hmdb-ucf/hmdb_train_source.txt"
  target_train_file: "txt/hmdb-ucf/ucf_train_target.txt"
  test_file: "txt/hmdb-ucf/ucf_test_target.txt"
  source_dataset: hmdb
  target_dataset: ucf
  root: "dataset/hmdb-ucf"